### ISSUE TITLE
Adhere to Airbnb Style Guide

### ISSUE THREAD

**Issue by superhackerboy** [superhackerboy/totally-random#29]
https://github.com/airbnb/javascript

I think this is our best option to have consistent code throughout the class. I did what I can but you'll notice there are more linting errors that I don't know how to fix/too afraid to mess with your guys' work.

**Comment by shadowtime2000** [comment]
I see those errors to but I rarely use linters so I do not know why they appear and how to fix them.

**Comment by Gridonyx** [comment]
I can go through it all when I refactor my code

**Comment by Gridonyx** [comment]
Alright, so I'm looking at my parts of the code and it is triggering eslint because I used bitwise operations. Removing the bitwise would require doing a complete rewrite of those sections of code despite there being nothing inherently wrong with using bitwise operations aside from them maybe getting misinterpreted as a typo for `&&` or `||`.

Can I just add an exception to the eslintrc file to allow bitwise?

**Comment by superhackerboy** [comment]
Yeah sure! What’s The docs say The reasoning is about using bitwise
Gridonyx <notifications@github.com> wrote:
“Alright, so I'm looking at my parts of the code and it is triggering eslint because I used bitwise operations. Removing the bitwise would require doing a complete rewrite of those sections of code despite there being nothing inherently wrong with using bitwise operations aside from them maybe getting misinterpreted as a typo for && or ||.

Can I just add an exception to the eslintrc file to allow bitwise?”

**Comment by Gridonyx** [comment]
@superhackerboy from eslint docs:
```
disallow bitwise operators (no-bitwise)

The use of bitwise operators in JavaScript is very rare and often & or | is simply a mistyped && or ||, which will lead to unexpected behavior.```

**Comment by superhackerboy** [comment]
Yeah I guess I don't care lmao. Add it to the exclusion
