### ISSUE TITLE
Are we good for 1.3?

### ISSUE THREAD

**Issue by superhackerboy** [superhackerboy/totally-random#50]
I want to publish it on NPM after I've done some manual testing. 

1. I noticed that running `npm test` returns "TypeError: TotallyRandom is not a constructor".
2. So when we need to make changes to the code, where do we do it? I'm not sure myself so this definitely needs to be in CONTRIBUTING.md

**Comment by shadowtime2000** [comment]
For the `TypeError` it is happening because we do not have a `module.exports` statement in `src/index.js` because `gulp-umd` wraps it and if a statement was there it wouldn't work. I believe we could just change the `require` inside of the test files to point to `dist` and then put it inside of the `CONTRIBUTING.md` that you need to run `gulp` or `npm run build` before you perform unit tests.

**Comment by shadowtime2000** [comment]
When we do need to make changes to the code we should be doing it inside `src/index.js`.

**Comment by superhackerboy** [comment]
So what happens in src/totallyRandom.js?

**Comment by shadowtime2000** [comment]
Nothing we should probably delete it.

**Comment by superhackerboy** [comment]
As well as index.js and the entire folder?

**Comment by shadowtime2000** [comment]
No because `src` is where we would make our changes and `gulp` will perform some stuff on it and output to `dist`

**Comment by superhackerboy** [comment]
Ok so keep src/index.js but delete src/totallyRandom.js

**Comment by shadowtime2000** [comment]
Yes.
